name = "verification-app"
compatibility_date = "2024-04-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "verify_db"
database_id = "93089b7c-9176-47fe-93e9-5b65add3afed"
